export const reducerCases ={
    SET_USER_INFO:"SET_USER_INFO",
    SET_NEW_USER:"SET_NEW_USER",
    SET_CONTACT_PAGE:"SET_CONTACT_PAGE",
    SET_CURRENT_CHAT_USER:"SET_CURRENT_CHAT_USER",
    SET_MESSAGES:"SET_MESSAGES",
    UPDATE_NEW_MESSAGES:"UPDATE_NEW_MESSAGES"

}